#https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server-properties
server:
   port: 8282
spring:
   profiles:
      active: git
   cloud:
      config:
         server:
            git:
               uri: https://github.com/arvindgupta1981/spring-config-server-configurations
logging:
   level:
      root: DEBUG