version: '3'
# create network by running sudo docker create network --driver bridge frontendnetwork
# default link in the same network all containers with service name
#sudo docker exec -it configurations-server-v01 ping eureka-service-registry-v01
networks:
 frontendnetwork:   
  external: true
services: 
 candidate-service:
  image: 'pc1204a/candidate-service:v01'
  #container_name: candidate-service
  links:
   - 'configurations-server'
   - 'eureka-service-registry'
   - 'mysqldb'
  networks:
   frontendnetwork:
    #ipv4_address: 172.21.0.11
  #expose:
   #- 8181
  ports:
   - '8181-8182:8181'
