#https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server-properties
server:
   port: 8282
spring:
   profiles:
      active: native
   cloud:
      config:
         server:
            native:
               searchLocations: file:D:/config/candidateservice